# 启动前加载
server:
  port: 9501
#  servlet:
#    context-path: /mi-controller
spring:
  application:
    name: mi-controller
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true
logging:
  path: d:\mymicroservice-log
#mi-api:
#   ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule 负载均衡配置 使用 随机策略

